### PR TITLE
CPOL-45 Waits for user before rendering the UI

### PR DESCRIPTION
**Pull request by josejulio**
This will present a Spinner until we get the user, ensuring that we only render if we are authenticated.

### CODE REVIEW

**Comment by pilhuhn** [comment]
Great idea.

During logging in, the big spinner says loading -- perhaps it would be better it said "logging in" ? Or if we did not show the table at all?

Bildschirmfoto 2020-01-15 um 20 38 36

**Comment by josejulio** [comment]
> Great idea.
> 
> During logging in, the big spinner says loading -- perhaps it would be better it said "logging in" ? Or if we did not show the table at all?

That's actually the loading from the table :)

The Loading that I added can't (or shouldn't, I'll double check) be differentiated from the loading of the "chrome".

**Comment by josejulio** [comment]
Mmh, they look different. oh well..

This is the chrome loading
Screenshot_2020-01-15_15-03-19

This is our wait-for-user loading
Screenshot_2020-01-15_15-03-02

**Comment by josejulio** [comment]
Ok, I updated the "loading-for-user", it will look equal to the "chrome-loading"
Screenshot_2020-01-15_15-03-19

I'll check the table loading to align it to the design style of Insights in a different PR.

**Comment by pilhuhn** [comment]
Not sure. The order of things still don't look right to me. The table + loading spinner already shows while the header still shows "logging in.." instead of my name.

**Comment by josejulio** [comment]
mmh  not sure what to make out of it, but before this PR you will get table loading and then an error (in console, 401, not authorized)

**Pull request merged**
