### PR TITLE
CPOL-44 Adds filtering to the Policy table

### PR DESCRIPTION
**Pull request by josejulio**
- Moved to insight's PrimaryToolbar component to match look and feel
- Changing the way the Insights var was being obtained

Peek 2020-02-14 12-11

Depends on https://github.com/RedHatInsights/custom-policies-ui-backend/pull/39
Depends on #44

### CODE REVIEW

**Comment by pilhuhn** [comment]
Should we prevent this combination, as this would always result in no output?

Bildschirmfoto 2020-02-18 um 15 43 32

**Comment by josejulio** [comment]
> Should we prevent this combination, as this would always result in no output?
> 
> Bildschirmfoto 2020-02-18 um 15 43 32

We can prevent that (changing to a radio button), but i'm interpreting it as "Active or Inactive", effectively removing the filter on the query (can be verified by checking the network tab)

**Comment by pilhuhn** [comment]
On 18 Feb 2020, at 15:59, Josejulio Martínez wrote:

> We can prevent that (changing to a radio button), but i'm interpreting 
> it as "Active or Inactive", effectively removing the filter on the 
> query (can be verified by checking the network tab)

Hm. This confuses me even more, that both checked == none checked.

Perhaps we ask Katie

**Comment by katierik** [comment]
> Should we prevent this combination, as this would always result in no output?
> 
> Bildschirmfoto 2020-02-18 um 15 43 32

This should have an output, it will have the entire list.

**Comment by katierik** [comment]
This filter is similar to the "rule status" filter in rules.
image

By default on open, only "Enabled" things are shown, so there is a filter chip (because the default is to show a subset). Since we are showing the entire list, we don't need the chip and "All" would be preselected.
Check out this behavior in CI

**Pull request merged**
